import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '@/components/global/Navbar'
import HomeHero from "@/components/home/HomeHero";
import Healthy from '@/components/home/Healthy'
import GetThat from '@/components/home/GetThat'
import Workout from '@/components/home/Workout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gym baran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <HomeHero />
        <Healthy />
        <GetThat />
        <Workout />
      </main>
    </>
  )
}
